# Generated by Django 4.2.3 on 2023-12-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
