# Generated by Django 4.2.3 on 2024-02-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=10)),
                ('address', models.CharField(default='', max_length=50)),
                ('pin', models.IntegerField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
