# Generated by Django 4.2.3 on 2024-02-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_rename_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.CharField(default='', max_length=100),
        ),
    ]
